// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxkorpmkhcbabocvbqsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4a29ycG1raGNiYWJvY3ZicXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDk1MjEsImV4cCI6MjA2MDE4NTUyMX0.wYTFbWnRzL4FAWSQW6mOIcOfKkF2ibafYAHtUfFnMKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);